version: "3.7"
services:
  db:
    # image: mysql:latest
    # image: mysql:5.7
    # image: fcumselab/progedu-mysql:latest
    build: ./mysql
    ports:
      - "${DB_PORT}:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      # MYSQL_USER: ${DB_USER}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
      # MYSQL_DATABASE: ${DB_DATABASE}

  gitlab:
    # image: gitlab/gitlab-ce
    # image: gitlab/gitlab-ce:10.8.5-ce.0
    # image: gitlab/gitlab-ce:10.0.0-ce.0
    image: gitlab/gitlab-ce:9.5.10-ce.0
    ports:
      - "${GITLAB_HTTP_PORT}:80"
      - "${GITLAB_SSH_PORT}:22"
    restart: always
    environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url '${GITLAB_HOST}'
          nginx['listen_port'] = 80
          nginx['listen_https'] = false
          gitlab_rails['initial_root_password'] = "${GITLAB_ROOT_PASSWORD}"
          gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
    depends_on:
        - db

  server:
    # image: fcumselab/progedu-server:latest
    # image: fcumselab/progedu-server:dev
    build:
      context: ./server
      args:
        - DEBUG=${DEBUG}
    environment:
      WEB_HOST: ${WEB_HOST}
      WEB_PORT: ${WEB_PORT}
      WEB_API_BASEURL: ${WEB_API_BASEURL}
      WEB_JENKINS_URL: ${WEB_JENKINS_URL}
      WEB_JENKINS_AUTO_LOGIN_URL: ${WEB_JENKINS_AUTO_LOGIN_URL}
      WEB_JENKINS_API_TOKEN: ${WEB_JENKINS_API_TOKEN}
      WEB_JENKINS_ADMIN_USERNAME: ${WEB_JENKINS_ADMIN_USERNAME}
      WEB_JENKINS_ADMIN_PASSWORD: ${WEB_JENKINS_ADMIN_PASSWORD}
      WEB_SELENIUM_URL: ${WEB_SELENIUM_URL}
      WEB_GITLAB_ADMIN_USERNAME: ${WEB_GITLAB_ADMIN_USERNAME}
      WEB_GITLAB_ADMIN_PERSONAL_TOKEN: ${WEB_GITLAB_ADMIN_PERSONAL_TOKEN}
      GITLAB_ROOT_PASSWORD: ${GITLAB_ROOT_PASSWORD}
      GITLAB_HOST: ${GITLAB_HOST}
      GITLAB_SSH_PORT: ${GITLAB_SSH_PORT}
      GITLAB_HTTP_PORT: ${GITLAB_HTTP_PORT}
      GITLAB_HTTPS_PORT: ${GITLAB_HTTPS_PORT}
      GITLAB_ENABLE_HTTPS: ${GITLAB_ENABLE_HTTPS}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    ports:
      - "${WEB_PORT}:8080"
    depends_on:
      - db

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "${JENKINS_PORT}:8080"
      - "30000:50000"
    restart: always
    volumes:
      - /home/server/web-test-workspace:/var/jenkins_home/workspace
    depends_on:
      - db

  selenium:
    image: selenium/standalone-chrome
    # ports:
    #   - "${SELENIUM_PORT}:4444"
    restart: always
    volumes:
      - /home/server/web-test-workspace:/var/lib/workspace
    depends_on:
      - db
